language: ruby
rvm:
  - 2.4.5
bundler_args: --without production
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake test
  - bundle exec cucumber -p first_try || true
  - bundle exec cucumber -p second_try
  #- cat tmp/capybara/*html
